In [1]:
import os
os.chdir("../")

In [2]:
from dataset import Dataset

In [3]:
dataset = Dataset()

In [7]:
dataset.get_overview_status()

                   Time   0   1   2   3   4   5   6   7   8  ...  4458  \
0   2008-05-17 00:00:00 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN
1   2008-05-17 01:00:00 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN
2   2008-05-17 02:00:00 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN
3   2008-05-17 03:00:00 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN
4   2008-05-17 04:00:00 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN
..                  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...   ...
581 2008-06-10 05:00:00 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN
582 2008-06-10 06:00:00 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN
583 2008-06-10 07:00:00 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN
584 2008-06-10 08:00:00 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN
585 2008-06-10 09:00:00 NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   NaN

         4459  4460  4461  4462  4463  4464  4465  4466  4467
0         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
3         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
4         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
..        ...   ...   ...   ...   ...   ...   ...   ...   ...
581       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
582  0.787714   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
583       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
584       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
585       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

[586 rows x 4469 columns]

In [9]:
road_tci_time_df = dataset._road_tci_time_df

In [10]:
road_tci_time_df['Hour'] = road_tci_time_df['Time'].dt.hour

In [21]:
road_tci_time_df = road_tci_time_df.groupby('Hour').mean(numeric_only=True)

In [34]:
road_tci_time_df.mean(axis=1).to_dict()

{0: 0.7704761056234434,
 1: 0.7865037000909311,
 2: 0.8108285204353713,
 3: 0.8196823136034128,
 4: 0.8275059026652765,
 5: 0.8356045799883658,
 6: 0.8442878329158012,
 7: 0.860963946114142,
 8: 0.8587830294622811,
 9: 0.8546806621346833,
 10: 0.8489339429674445,
 11: 0.8488280103330968,
 12: 0.8501069760206428,
 13: 0.8434146794308184,
 14: 0.8215312168691685,
 15: 0.7918365929133344,
 16: 0.7944112165482774,
 17: 0.7936475713922598,
 18: 0.7951376629838479,
 19: 0.7862125370594321,
 20: 0.7863377946625307,
 21: 0.7812700646063913,
 22: 0.7790271681273219,
 23: 0.7689352278662859}

In [51]:
road_tci_time_df

,0,1,2,3,4,5,6,7,8,9,...,4458,4459,4460,4461,4462,4463,4464,4465,4466,4467
Hour,,,,,,,,,,,,,,,,,,,,,
0,0.976236,0.554956,0.822366,0.842028,NaN,NaN,NaN,NaN,NaN,0.552081,...,NaN,0.699265,NaN,0.752623,0.920586,0.578506,0.885725,0.409248,0.607685,NaN
1,NaN,0.243510,0.567132,0.781727,NaN,NaN,NaN,NaN,NaN,1.096913,...,1.079738,0.876289,0.654785,0.719298,0.847544,0.938598,0.918903,0.899460,0.818234,NaN
2,0.758837,NaN,0.403834,0.947523,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.891979,0.841886,0.978352,0.734902,0.718135,1.075492,0.730919,0.884095,0.256297
3,NaN,NaN,0.659000,1.004327,NaN,NaN,NaN,NaN,NaN,0.490473,...,0.732812,0.907079,0.755992,0.841158,0.701152,0.851806,1.028647,0.705599,1.001602,0.562373
4,1.137873,NaN,1.221994,0.897339,NaN,NaN,NaN,NaN,NaN,NaN,...,0.870101,0.865957,0.448381,0.754252,0.824389,0.650444,0.818468,1.105084,0.836131,0.090049
5,0.918136,NaN,0.814564,0.862632,NaN,NaN,NaN,NaN,1.000000,NaN,...,1.007938,0.913792,0.732995,0.801987,0.826332,0.803427,1.029138,0.682670,0.896092,1.073889
6,NaN,NaN,NaN,0.850604,NaN,NaN,NaN,NaN,NaN,NaN,...,1.145490,0.956660,0.974616,0.705037,0.415622,0.907935,1.075021,0.782423,0.996465,NaN
7,NaN,NaN,NaN,0.984411,NaN,NaN,NaN,NaN,NaN,NaN,...,0.658670,1.060901,1.306157,0.875394,0.778787,0.850520,1.145665,0.756212,0.739100,NaN
8,1.062053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.769207,1.029044,1.110309,1.052787,1.024457,0.602445,1.081476,0.770250,0.882472,NaN
9,0.647716,NaN,0.692304,1.008227,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.107742,1.111889,1.087556,1.231959,0.818711,1.158191,0.559916,0.943424,NaN
10,NaN,NaN,NaN,1.238650,1.0,NaN,NaN,NaN,NaN,1.004325,...,0.513510,1.014013,1.202873,1.031484,0.897411,0.801949,0.991212,0.676599,0.634196,NaN
11,NaN,NaN,NaN,0.854882,NaN,NaN,NaN,NaN,NaN,NaN,...,1.339194,1.106909,1.282832,1.036266,1.113704,0.837650,0.946636,0.591281,0.942045,1.486569
12,NaN,NaN,NaN,0.930798,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.141326,NaN,0.966562,1.016889,0.930380,1.280058,0.656972,0.867319,NaN
13,1.000000,NaN,0.867425,1.037256,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.923716,NaN,0.816158,0.832930,1.005367,0.822768,0.921663,0.948387,NaN
14,0.921624,NaN,0.768555,0.946703,NaN,NaN,NaN,NaN,NaN,0.423089,...,0.526829,0.840144,0.150366,0.726225,0.710120,1.021593,0.952681,0.881630,0.894893,NaN
15,NaN,0.152172,0.366077,0.934416,NaN,NaN,NaN,NaN,NaN,0.407064,...,1.000000,0.852398,0.644688,0.682340,0.876434,0.669477,0.892337,NaN,0.697599,NaN
16,NaN,0.295974,0.800632,0.834534,NaN,NaN,NaN,NaN,NaN,NaN,...,0.309906,0.775460,0.821889,0.697237,0.694806,0.688096,0.767380,0.847669,0.726359,0.719767
17,NaN,NaN,0.794703,0.914879,NaN,NaN,NaN,NaN,NaN,NaN,...,0.210551,0.831899,0.760842,0.617758,0.097682,0.782311,0.658969,0.741959,0.513277,0.734735
18,0.581744,1.098169,0.996995,0.939735,NaN,NaN,NaN,NaN,NaN,0.436782,...,NaN,0.703691,0.745046,0.586719,1.027055,0.779029,0.860450,0.496680,0.490805,0.479056
19,NaN,NaN,NaN,0.988224,NaN,NaN,NaN,NaN,NaN,0.676992,...,0.276168,0.738839,0.182612,0.582700,0.744140,0.542847,0.743740,0.781334,0.620661,0.481446
20,NaN,1.000000,0.558712,0.966716,NaN,NaN,NaN,NaN,NaN,0.250665,...,0.628548,0.667734,0.927996,0.500225,NaN,0.652735,0.747263,NaN,0.821829,0.729093
21,0.867862,NaN,0.560796,0.914651,NaN,NaN,NaN,NaN,NaN,0.709446,...,NaN,0.690139,0.366099,0.551304,0.522666,0.562029,0.637487,0.569720,0.615633,0.666411
22,NaN,NaN,0.745744,0.976819,NaN,NaN,NaN,NaN,0.208342,0.908307,...,0.844213,0.771795,0.634321,0.695289,0.539795,0.581432,0.935261,0.773975,0.721715,0.644656
23,NaN,1.207938,0.508642,0.865910,NaN,NaN,NaN,NaN,NaN,0.843546,...,NaN,0.648125,0.465906,0.671710,0.873320,0.812617,0.888419,0.574815,0.870200,NaN

In [55]:
road_tci_time_df.applymap(lambda x: 1 if x <= 0.4 else 0).sum(axis=1).to_dict()

{0: 119,
 1: 108,
 2: 101,
 3: 106,
 4: 90,
 5: 100,
 6: 107,
 7: 93,
 8: 118,
 9: 149,
 10: 182,
 11: 174,
 12: 144,
 13: 127,
 14: 122,
 15: 120,
 16: 116,
 17: 131,
 18: 116,
 19: 107,
 20: 96,
 21: 115,
 22: 128,
 23: 124}